### PR TITLE
Fix navigation wrap

### LINKED ISSUE #71: Width threshold for vertical menu is too low
Our menu items are wider than those used on the original terminal.css webpage, so the width threshold for switching the menu layout is a bit too low. At some widths, the menu can clip through itself:

Image

### PR DESCRIPTION
**Pull request by amazingca**
closes #71

### CODE REVIEW

File: src/lib/Navigation.svelte [hunk 1]
```diff
@@ -76,11 +76,28 @@
...
+		}
+		.terminal-menu ul {
+		  flex-direction: column;
+		  align-items: flex-start;
+		  margin-top: 0;
+    }
+    .terminal-menu li {
+    	margin: 0 0 0.5em;
+    }
+  }
```
Comment (lewark) [inline src/lib/Navigation.svelte]: Something seems to have happened with the indentation here

**Review by lewark — COMMENTED** [review]
Looks good overall. Did notice a small indentation issue, but that's about it.

File: src/lib/Navigation.svelte (hunk 1 above)
Comment (amazingca) [reply src/lib/Navigation.svelte]: That is unusual. Let me take a look at this.

Comment (amazingca) [reply src/lib/Navigation.svelte]: Should be resolved now.

**Review by lewark — APPROVED** [review]
